<#
.SYNOPSIS
  Run MeowFlixEmby at user login WITHOUT installing a Windows service.

.DESCRIPTION
  Registers the daemon as a per-user startup item under
  HKCU\Software\Microsoft\Windows\CurrentVersion\Run. This runs in your
  interactive desktop session (so it can launch a player) and needs NO admin
  rights — unlike the service (install-service.ps1), which runs in session 0.

  Use this OR the service, not both.

  By default the console window is hidden via a generated .vbs launcher. Set
  the log file in your config (log.file) so you still get logs.

.PARAMETER Action
  install | uninstall | status   (default: install)

.PARAMETER Exe
  Path to meowflix.exe. Defaults to meowflix.exe next to this script.

.PARAMETER Config
  Path to the config file. Defaults to meowflix.yaml next to the exe.

.PARAMETER ShowWindow
  Keep the console window visible instead of hiding it.

.EXAMPLE
  .\setup-autostart.ps1 -Action install -Exe C:\meowflix\meowflix.exe -Config C:\meowflix\meowflix.yaml
  .\setup-autostart.ps1 -Action status
  .\setup-autostart.ps1 -Action uninstall
#>
param(
    [ValidateSet('install', 'uninstall', 'status')]
    [string]$Action = 'install',
    [string]$Exe,
    [string]$Config,
    [switch]$ShowWindow
)

$ErrorActionPreference = 'Stop'

$RunKey    = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
$ValueName = 'MeowFlixEmby'
$LauncherName = 'meowflix-autostart.vbs'

function Get-LauncherPath {
    Join-Path $env:LOCALAPPDATA "MeowFlixEmby\$LauncherName"
}

switch ($Action) {
    'status' {
        $existing = (Get-ItemProperty -Path $RunKey -Name $ValueName -ErrorAction SilentlyContinue).$ValueName
        if ($existing) {
            Write-Host "autostart: ENABLED"
            Write-Host "  command: $existing"
        } else {
            Write-Host "autostart: not configured"
        }
        break
    }

    'uninstall' {
        Remove-ItemProperty -Path $RunKey -Name $ValueName -ErrorAction SilentlyContinue
        $launcher = Get-LauncherPath
        if (Test-Path $launcher) { Remove-Item $launcher -Force }
        Write-Host "autostart removed."
        break
    }

    'install' {
        if (-not $Exe) { $Exe = Join-Path $PSScriptRoot 'meowflix.exe' }
        if (-not (Test-Path $Exe)) { throw "meowflix.exe not found at '$Exe'. Pass -Exe <path>." }
        $Exe = (Resolve-Path $Exe).Path

        if (-not $Config) { $Config = Join-Path (Split-Path $Exe -Parent) 'meowflix.yaml' }
        if (-not (Test-Path $Config)) { Write-Warning "config not found at '$Config' — it must exist at login." }
        else { $Config = (Resolve-Path $Config).Path }

        if ($ShowWindow) {
            # Run the exe directly; a console window will be visible.
            $command = "`"$Exe`" -config `"$Config`""
        } else {
            # Generate a .vbs launcher that starts the exe with a hidden window.
            $launcher = Get-LauncherPath
            $launcherDir = Split-Path $launcher -Parent
            if (-not (Test-Path $launcherDir)) { New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null }
            $vbs = @"
' Auto-generated by setup-autostart.ps1 - launches MeowFlixEmby with a hidden window.
Set sh = CreateObject("WScript.Shell")
sh.Run """$Exe"" -config ""$Config""", 0, False
"@
            Set-Content -Path $launcher -Value $vbs -Encoding ASCII
            $command = "wscript.exe `"$launcher`""
        }

        Set-ItemProperty -Path $RunKey -Name $ValueName -Value $command
        Write-Host "autostart installed (runs at next login for current user)."
        Write-Host "  command: $command"
        Write-Host "Tip: set 'log.file' in your config so you still capture logs with the window hidden."
        break
    }
}
